#!/usr/bin/env node

/**
 * Flyway Dashboard Server - Interactive Setup Wizard
 * 
 * This wizard guides you through:
 * - Environment configuration
 * - JDBC connection setup
 * - Database connectivity testing
 * - Initial data generation
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Pool } = require('pg');
const sql = require('mssql');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Color codes for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  blue: '\x1b[34m'
};

function colorize(text, color) {
  return `${colors[color]}${text}${colors.reset}`;
}

function header(text) {
  console.log('\n' + colorize('='.repeat(60), 'cyan'));
  console.log(colorize(`  ${text}`, 'bright'));
  console.log(colorize('='.repeat(60), 'cyan') + '\n');
}

function success(text) {
  console.log(colorize(`✓ ${text}`, 'green'));
}

function warning(text) {
  console.log(colorize(`⚠ ${text}`, 'yellow'));
}

function error(text) {
  console.log(colorize(`✗ ${text}`, 'red'));
}

function info(text) {
  console.log(colorize(`ℹ ${text}`, 'blue'));
}

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(colorize(prompt, 'cyan'), (answer) => {
      resolve(answer.trim());
    });
  });
}

function questionWithDefault(prompt, defaultValue) {
  return new Promise((resolve) => {
    rl.question(
      colorize(`${prompt} `, 'cyan') + colorize(`[${defaultValue}]`, 'yellow') + ': ',
      (answer) => {
        resolve(answer.trim() || defaultValue);
      }
    );
  });
}

async function confirm(prompt, defaultYes = true) {
  const suffix = defaultYes ? '[Y/n]' : '[y/N]';
  const answer = await question(`${prompt} ${suffix}: `);
  const normalized = answer.toLowerCase();
  
  if (!normalized) return defaultYes;
  return normalized === 'y' || normalized === 'yes';
}

// Test PostgreSQL connection
async function testPostgresConnection(jdbcUrl) {
  const urlMatch = jdbcUrl.match(/^jdbc:postgresql:\/\/([^:/]+)(?::(\d+))?\/([^?]+)\??(.*)$/);
  if (!urlMatch) {
    error('Invalid PostgreSQL JDBC URL format');
    return false;
  }
  
  const [, host, port, database, query] = urlMatch;
  let user, password;
  if (query) {
    const params = new URLSearchParams(query);
    user = params.get('user');
    password = params.get('password');
  }
  
  const config = {
    host,
    port: port ? parseInt(port) : 5432,
    database,
    user,
    password
  };
  
  const pool = new Pool(config);
  try {
    await pool.query('SELECT 1');
    await pool.query('SELECT COUNT(*) FROM flyway_schema_history');
    await pool.end();
    return true;
  } catch (e) {
    await pool.end();
    error(`Connection failed: ${e.message}`);
    return false;
  }
}

// Test SQL Server connection
async function testMssqlConnection(jdbcUrl) {
  const serverMatch = jdbcUrl.match(/jdbc:sqlserver:\/\/([^:;]+)(?::(\d+))?/);
  const dbMatch = jdbcUrl.match(/databaseName=([^;]+)/);
  const userMatch = jdbcUrl.match(/user=([^;]+)/);
  const passwordMatch = jdbcUrl.match(/password=([^;]+)/);
  
  if (!serverMatch || !dbMatch) {
    error('Invalid SQL Server JDBC URL format');
    return false;
  }
  
  const config = {
    server: serverMatch[1],
    port: serverMatch[2] ? parseInt(serverMatch[2]) : 1433,
    database: dbMatch[1],
    user: userMatch ? userMatch[1] : '',
    password: passwordMatch ? passwordMatch[1] : '',
    options: {
      trustServerCertificate: true,
      encrypt: true,
      enableArithAbort: true,
      connectTimeout: 10000,
      requestTimeout: 10000
    }
  };
  
  try {
    const pool = await sql.connect(config);
    await pool.request().query('SELECT 1');
    await pool.request().query('SELECT COUNT(*) FROM flyway_schema_history');
    await pool.close();
    return true;
  } catch (e) {
    error(`Connection failed: ${e.message}`);
    return false;
  }
}

// Generate encryption key
function generateEncryptionKey() {
  return crypto.randomBytes(32).toString('hex');
}

// Save .env file
function saveEnvFile(config) {
  const envPath = path.join(__dirname, '.env');
  const envContent = `# Flyway Dashboard Server Configuration
# Generated by setup wizard on ${new Date().toISOString()}

# Demo Mode
DEMO_MODE=${config.demoMode}

# Server Port
PORT=${config.port}

# CORS Allowed Origins
ALLOWED_ORIGINS=${config.allowedOrigins}

# Encryption Key (KEEP SECRET!)
JDBC_ENCRYPTION_KEY=${config.encryptionKey}

# Database Credentials (if needed)
POSTGRES_USER=${config.postgresUser || ''}
POSTGRES_PASSWORD=${config.postgresPassword || ''}
MSSQL_USER=${config.mssqlUser || ''}
MSSQL_PASSWORD=${config.mssqlPassword || ''}
`;
  
  fs.writeFileSync(envPath, envContent, 'utf8');
  success('.env file created');
}

// Save JDBC connections
function saveJdbcConnections(connections) {
  const jdbcPath = path.join(__dirname, 'jdbc-connections.json');
  fs.writeFileSync(jdbcPath, JSON.stringify(connections, null, 2), 'utf8');
  success('jdbc-connections.json saved');
}

async function setupEnvironment() {
  header('Environment Configuration');
  
  const config = {};
  
  // Demo mode
  info('Demo mode uses sample data for testing without database connections.');
  config.demoMode = await confirm('Enable demo mode?', false);
  
  // Server port
  config.port = await questionWithDefault('Server port', '3001');
  
  // CORS origins
  info('Enter the URL where your React UI will be hosted (e.g., http://localhost:3000)');
  config.allowedOrigins = await questionWithDefault('Allowed CORS origins', 'http://localhost:3000');
  
  // Encryption key
  info('Generating secure encryption key for JDBC credentials...');
  config.encryptionKey = generateEncryptionKey();
  success('Encryption key generated');
  
  return config;
}

async function setupJdbcConnections() {
  header('JDBC Database Connections');
  
  const connections = {
    prod: [],
    nonProd: []
  };
  
  if (await confirm('Add production database connections?', true)) {
    let addMore = true;
    while (addMore) {
      console.log('');
      info('Enter JDBC URL for production database');
      info('Examples:');
      info('  PostgreSQL: jdbc:postgresql://localhost:5432/mydb?user=postgres&password=secret');
      info('  SQL Server: jdbc:sqlserver://localhost:1433;databaseName=mydb;user=sa;password=secret');
      
      const jdbcUrl = await question('JDBC URL: ');
      
      if (jdbcUrl) {
        // Test connection
        info('Testing connection...');
        let connected = false;
        
        if (jdbcUrl.startsWith('jdbc:postgresql://')) {
          connected = await testPostgresConnection(jdbcUrl);
        } else if (jdbcUrl.startsWith('jdbc:sqlserver://')) {
          connected = await testMssqlConnection(jdbcUrl);
        } else {
          error('Unsupported database type (only PostgreSQL and SQL Server)');
        }
        
        if (connected) {
          success('Connection successful!');
          connections.prod.push(jdbcUrl);
        } else {
          warning('Connection failed, but you can still add it (fix credentials later)');
          if (await confirm('Add anyway?', false)) {
            connections.prod.push(jdbcUrl);
          }
        }
      }
      
      addMore = await confirm('Add another production database?', false);
    }
  }
  
  if (await confirm('Add non-production (test/QA) database connections?', true)) {
    let addMore = true;
    while (addMore) {
      console.log('');
      const jdbcUrl = await question('Non-prod JDBC URL: ');
      
      if (jdbcUrl) {
        info('Testing connection...');
        let connected = false;
        
        if (jdbcUrl.startsWith('jdbc:postgresql://')) {
          connected = await testPostgresConnection(jdbcUrl);
        } else if (jdbcUrl.startsWith('jdbc:sqlserver://')) {
          connected = await testMssqlConnection(jdbcUrl);
        }
        
        if (connected) {
          success('Connection successful!');
          connections.nonProd.push(jdbcUrl);
        } else {
          warning('Connection failed, but you can still add it');
          if (await confirm('Add anyway?', false)) {
            connections.nonProd.push(jdbcUrl);
          }
        }
      }
      
      addMore = await confirm('Add another non-production database?', false);
    }
  }
  
  return connections;
}

async function generateDemoData() {
  header('Demo Data Generation');
  
  if (await confirm('Generate sample lead time data for testing?', true)) {
    try {
      info('Generating demo data...');
      const { execSync } = require('child_process');
      execSync('node refresh-all-demo-data.js', { stdio: 'inherit' });
      success('Demo data generated');
    } catch (e) {
      error(`Demo data generation failed: ${e.message}`);
    }
  }
}

async function showSummary(config, connections) {
  header('Setup Summary');
  
  console.log(colorize('Environment:', 'bright'));
  console.log(`  Demo Mode: ${config.demoMode}`);
  console.log(`  Server Port: ${config.port}`);
  console.log(`  Allowed Origins: ${config.allowedOrigins}`);
  console.log(`  Encryption: Enabled (AES-256-GCM)`);
  
  console.log('\n' + colorize('Database Connections:', 'bright'));
  console.log(`  Production: ${connections.prod.length} database(s)`);
  console.log(`  Non-Production: ${connections.nonProd.length} database(s)`);
  
  console.log('\n' + colorize('Next Steps:', 'bright'));
  console.log('  1. Start the server: npm start');
  console.log('  2. Test health endpoint: curl http://localhost:' + config.port + '/health');
  console.log('  3. Access dashboard UI at: http://localhost:3000');
  
  console.log('\n' + colorize('Configuration Files:', 'bright'));
  console.log('  .env - Environment variables');
  console.log('  jdbc-connections.json - Database connections (encrypted at runtime)');
  
  console.log('');
}

async function main() {
  console.clear();
  
  header('Flyway Dashboard Server - Setup Wizard');
  
  info('This wizard will help you configure the Flyway Dashboard server.');
  info('You can modify settings later by editing .env and jdbc-connections.json');
  console.log('');
  
  if (!await confirm('Continue with setup?', true)) {
    info('Setup cancelled');
    rl.close();
    return;
  }
  
  try {
    // Step 1: Environment
    const config = await setupEnvironment();
    
    // Step 2: JDBC connections (skip if demo mode)
    let connections = { prod: [], nonProd: [] };
    if (!config.demoMode) {
      connections = await setupJdbcConnections();
    } else {
      info('Skipping JDBC setup (demo mode enabled)');
    }
    
    // Step 3: Save configuration
    header('Saving Configuration');
    saveEnvFile(config);
    saveJdbcConnections(connections);
    
    // Step 4: Generate demo data
    await generateDemoData();
    
    // Step 5: Summary
    await showSummary(config, connections);
    
    success('Setup complete! 🚀');
    
  } catch (e) {
    error(`Setup failed: ${e.message}`);
    console.error(e);
  } finally {
    rl.close();
  }
}

// Run wizard
main();
